### ISSUE TITLE
Inner product 'auto1' error during Multivariate Functional Isolation Forest when alpha = 0.5

### ISSUE THREAD

**Issue by lorebon** [GuillaumeStaermanML/FIF#5]
When performing a Multivariate FIF using the 'auto1' inner product, if parameter 'alpha' is set to 0.5 I obtain the following error:

>File "mtrand.pyx", line 1110, in numpy.random.mtrand.RandomState.uniform
>OverflowError: Range exceeds valid bounds

I kindly ask for your assistance. Thanks in advance!

**Comment by GuillaumeStaermanML** [comment]
Unfortunately, it may happen for some dataset where the norm of functions of the normalization in the Sobolev inner product (alpha=0.5) is very close to zero.

**Comment by lorebon** [comment]
> Unfortunately, it may happen for some dataset where the norm of functions of the normalization in the Sobolev inner product (alpha=0.5) is very close to zero.

OK, I understand now. Thanks!
